module.exports = [
  {
    title: "Lorem Ipsum 1",
    subtitle: "Anim id est laborum.",
    paragraphs: [
      "Lorem ipsum dolor sit amet. Et voluptatum internos aut delectus autem aut tempora eius ut impedit incidunt in Quis unde. Non dolorem rerum sed repellendus beatae id ipsam exercitationem et dolores eveniet. Sit quam esse 33 maxime fuga ut aperiam distinctio id autem enim ut laborum quaerat est reprehenderit amet? Est voluptatem assumenda vel dolores incidunt nam odit amet. Et ipsa doloremque quo molestiae recusandae aut minima voluptatem in omnis tempore hic ipsam libero sed iste illum. Et ducimus fugit eum doloremque similique et tempore doloremque est dolore nostrum aut quia voluptas. Ea velit reiciendis non minima labore sit similique error qui omnis debitis in consequatur officiis?",
      "Est accusantium officia est quasi galisum aut quod cupiditate. Est totam fugiat vel autem nihil sit quam accusamus qui quae deleniti ut asperiores Quis. 33 illo error ex aspernatur exercitationem eum neque vero? Hic obcaecati aliquid cum deleniti accusantium sit nulla tempore est earum iste. Et sint architecto qui cumque tempora et optio distinctio. Aut perspiciatis rerum cum molestiae expedita et asperiores quia sit voluptates dolore qui labore maxime! Qui similique optio ut dolore fuga cum nemo Quis id veritatis impedit.",
      "Hic doloribus amet et eius voluptatem et explicabo laudantium 33 eligendi minima sit consectetur pariatur vel esse quod qui nulla iste. Quo repellendus quia ut incidunt eligendi a voluptatem ullam sit magni magnam. Aut velit quasi sed repellat rerum et rerum explicabo ut veniam excepturi aut porro beatae eos laudantium tempora et excepturi ipsum. Sed cupiditate ducimus ut enim placeat At iusto omnis et voluptates dignissimos est nulla dolorem qui totam animi est laudantium unde. Et veritatis sint ut sunt error sit assumenda adipisci in dolorem soluta veniam vero. Qui soluta reprehenderit soluta reprehenderit ea suscipit nihil sit minus ipsa qui excepturi quos. Qui dignissimos dignissimos cum alias velit ea laborum porro. A vitae suscipit et aspernatur laboriosam ex animi beatae non molestiae assumenda minima fuga. Aut facere repudiandae id voluptatem nobis est voluptas dolor aut unde expedita!",
      "Ut dolores quasi et dolore voluptatem est inventore commodi et galisum unde qui repellat magnam. Qui rerum nisi et blanditiis amet qui quisquam libero! Nam autem cumque aut internos internos est dignissimos architecto ut neque neque non nemo quisquam quo tempore exercitationem. Ea galisum fugiat et libero voluptas vel recusandae quaerat. Ex doloribus tempore ut quasi laborum et autem velit qui soluta maxime sit aspernatur ipsum. Qui omnis dignissimos vel facilis dolore ab illo. Ab odio quisquam eum quidem cum consequatur placeat ut eveniet modi ut voluptatibus fuga sed facere. Et galisum distinctio id quam inventore ut saepe blanditiis. Aut sint incidunt et galisum similique quo deleniti delectus.",
      "Aut perspiciatis quibusdam ea natus sint sed facilis consequatur et autem ipsa in ipsum nemo et impedit dicta ad natus praesentium. Est voluptatem ipsum aut explicabo atque quo ipsum eligendi est officia fugiat. Et enim minima et pariatur reprehenderit et impedit tempore quo molestiae tempora eos expedita incidunt sed explicabo quos sit repudiandae possimus. In enim excepturi in corporis voluptas est internos impedit! A autem consequuntur et minima facilis aut laborum fugiat hic assumenda laudantium."
    ]
  },
  {
    title: "Lorem Ipsum 2",
    subtitle: "No ut enim ad minim veniam.",
    paragraphs: [
      "Hic porro consequatur sed eligendi explicabo id libero alias ut repellat repudiandae. Et veniam quia cum corrupti unde vel quos officiis ex quia repellat. Non voluptatem consequuntur sit illum expedita in eveniet illo et esse porro At quibusdam laboriosam non Quis maxime. Aut autem ipsum ut sint earum qui necessitatibus laboriosam ea nihil unde. Sed corrupti numquam At architecto distinctio ut ratione esse. Quod quia ut velit natus et ratione alias ad dolore accusamus et voluptatem dolore sit temporibus minima vel dolores officia. Et asperiores est minus voluptas ut vitae accusantium qui animi similique id possimus iusto.",
      "Sit earum esse eos aliquid placeat est cupiditate beatae qui adipisci quia non maxime vero. Qui internos tempore ut illo ratione At laborum laborum sit voluptatem atque 33 praesentium temporibus aut consequatur natus et suscipit temporibus? A laboriosam incidunt qui doloremque vitae est atque quos et magni quia non maxime dignissimos quo pariatur repellendus. Ut atque saepe aut nihil quod quo necessitatibus perferendis a veritatis recusandae aut distinctio dolorem? Et architecto fugiat 33 labore voluptate et galisum placeat est esse alias sit voluptate eaque quo illum porro et consequatur fuga. Sit reiciendis quisquam est aspernatur nihil in commodi magnam ex minus facere ut galisum debitis sed dolores quia? Eos officia blanditiis quo rerum libero est illum itaque. Non necessitatibus velit ut molestiae exercitationem non consequatur voluptatem. Aut quae iste et omnis asperiores aut cupiditate omnis voluptate nemo.",
      "Ea adipisci dolor et aperiam voluptatem quo amet eveniet qui inventore voluptatum. Qui accusantium perspiciatis et ipsa eligendi in excepturi magni aut cumque voluptas rem iste officiis ut expedita minima et tempora quam. Id enim animi et inventore exercitationem rem nulla veritatis et doloremque incidunt aut ipsa voluptatem vel asperiores internos eos optio ratione. Nam ipsum cumque qui iusto voluptates dolore consequuntur et deserunt voluptas qui soluta error. Est magni sequi ut aperiam ratione est consequatur repudiandae est maxime atque."
    ]
  }
];